server:
  port: 6608

spring:
  application:
    name: carrentals-service

  datasource:
    url: jdbc:mysql://localhost:3306/carrentals_db
    username: root
    password: MySQL@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6610/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
