server:
  port: 6607

spring:
  application:
    name: passenger-service
  config:
    import: "optional:configserver:http://localhost:6609"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6610/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
